# .github/workflows/ci.yml
name: CI – Lint & Tests

on:
  pull_request:
    branches: [ main ]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dev dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest flake8

      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 --max-line-length=88 .

      - name: Run tests
        run: |
          pytest --maxfail=1 --disable-warnings -q
